name: Test Workflow
on:
  push:
    branches: [main]
    paths:
      - "src/**" # Dieser Workflow wird nur ausgelöst, wenn Dateien im Ordner "src" geändert werden
  pull_request:
    paths:
      - "src/**"
  workflow_dispatch: # Ermöglicht das manuelle Auslösen des Workflows

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo, rockn´n roll
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Run tests
        run: mvn -B -DiskTests=false test

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
